### PR TITLE
[Fix #1] add personal_listAccounts

### LINKED ISSUE #1: personal_* missing
The `personal_listAccounts` RPC call is missing. Parity maps it here 

https://github.com/ethcore/parity/blob/master/rpc/src/v1/traits/personal.rs#L39
https://github.com/ethcore/parity/blob/master/rpc/src/v1/impls/personal.rs#L50

Also `personal_signerEnabled` as per comment below.

### PR DESCRIPTION
**Pull request by jacogr**
Fixes #1
https://github.com/ethcore/ethereum-rpc-json/issues/1

### CODE REVIEW

**Comment by tomusdrw** [comment]
Can you also regenerate `rpc.json` (probably we need to do it automatically in future, or better -we ditch the generator)

**Comment by jacogr** [comment]
Should also add `personal_signerEnabled` in this one.

**Comment by tomusdrw** [comment]
It returns `bool` (but subject to change soon) I will make a separate issue for `personal_signerEnabled`

**Comment by goldylucks** [comment]
@jacogr this was closed via #6 ?

**Comment by jacogr** [comment]
Closed via #6

**Pull request closed without merging**
